import type { Experience } from "./types";

export const experiences: Experience[] = [
  {
    id: "cafe-exp-1",
    slug: "cafe-experience-1",
    offeringId: "cafe-collective",
    title: "Café Gathering Experience 01",
    teaser: "Placeholder teaser for Café Gathering Experience 01.",
    description: "Placeholder description for Café Gathering Experience 01.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Café Gathering Experience 01",
      description: "Placeholder SEO description for Café Gathering Experience 01.",
    },
  },
  {
    id: "cafe-exp-2",
    slug: "cafe-experience-2",
    offeringId: "cafe-collective",
    title: "Café Gathering Experience 02",
    teaser: "Placeholder teaser for Café Gathering Experience 02.",
    description: "Placeholder description for Café Gathering Experience 02.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Café Gathering Experience 02",
      description: "Placeholder SEO description for Café Gathering Experience 02.",
    },
  },
  {
    id: "cafe-exp-3",
    slug: "cafe-experience-3",
    offeringId: "cafe-collective",
    title: "Café Gathering Experience 03",
    teaser: "Placeholder teaser for Café Gathering Experience 03.",
    description: "Placeholder description for Café Gathering Experience 03.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Café Gathering Experience 03",
      description: "Placeholder SEO description for Café Gathering Experience 03.",
    },
  },
  {
    id: "cafe-exp-4",
    slug: "cafe-experience-4",
    offeringId: "cafe-collective",
    title: "Café Gathering Experience 04",
    teaser: "Placeholder teaser for Café Gathering Experience 04.",
    description: "Placeholder description for Café Gathering Experience 04.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Café Gathering Experience 04",
      description: "Placeholder SEO description for Café Gathering Experience 04.",
    },
  },
  {
    id: "half-day-exp-1",
    slug: "half-day-experience-1",
    offeringId: "half-day-experience",
    title: "Half-Day Experiential Journey 01",
    teaser: "Placeholder teaser for Half-Day Journey 01.",
    description: "Placeholder description for Half-Day Journey 01.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Half-Day Experiential Journey 01",
      description: "Placeholder SEO description for Half-Day Journey 01.",
    },
  },
  {
    id: "half-day-exp-2",
    slug: "half-day-experience-2",
    offeringId: "half-day-experience",
    title: "Half-Day Experiential Journey 02",
    teaser: "Placeholder teaser for Half-Day Journey 02.",
    description: "Placeholder description for Half-Day Journey 02.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Half-Day Experiential Journey 02",
      description: "Placeholder SEO description for Half-Day Journey 02.",
    },
  },
  {
    id: "half-day-exp-3",
    slug: "half-day-experience-3",
    offeringId: "half-day-experience",
    title: "Half-Day Experiential Journey 03",
    teaser: "Placeholder teaser for Half-Day Journey 03.",
    description: "Placeholder description for Half-Day Journey 03.",
    highlights: ["Placeholder highlight 1", "Placeholder highlight 2"],
    seo: {
      title: "Half-Day Experiential Journey 03",
      description: "Placeholder SEO description for Half-Day Journey 03.",
    },
  },
];
